[package]
name = "qcat"
version = "0.1.0"
authors = ["croy <craigr63@gmail.com>"]

[dependencies]
hyper = "*"
hyper-tls = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
cursive = "*"
futures = "*"